spring:
  profiles:
    active: instance3
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false #由于该应用为注册中心,设置为false,表明不向注册中心注册自己
  server:
    enable-self-preservation: false # 关闭自我保护
    fetch-registry: false #是否从eureka服务器获取注册信息，这里不需要
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: instance1
server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka/

---
spring:
  profiles: instance2
server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8763/eureka/

---
spring:
  profiles: instance3
server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka/